version: '3.9'
services:
  client:
    build: client
    ports:
      - '3000:3000'
  games:
    build: games
    ports:
      - '4001:4001'
  event-bus:
    build: event-bus
    ports:
      - '4005:4005'
  players:
    build: players
    ports:
      - '4000:4000'
  query:
    build: query
    ports:
      - '4002:4002'